apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-hub-controller
  labels:
    app: work-hub-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work-hub-controller
  template:
    metadata:
      labels:
        app: work-hub-controller
    spec:
      serviceAccountName: work-hub-sa
      containers:
      - name: work-hub-controller
        image: quay.io/open-cluster-management/work:latest
        imagePullPolicy: Always
        args:
          - "/work"
          - "manager"
          - "--disable-leader-election"
          - "--mqtt-broker-host=mosquitto:1883"
          - "--mqtt-username=admin"
          - "--mqtt-password=password"
          - "--mqtt-sub-topic=clusters/+/manifestsstatus"
          - "--mqtt-pub-topic=clusters/+/manifests"
          - "--mqtt-resync-request-topic=resync/clusters/manifestsstatus"
          - "--mqtt-resync-response-topic=resync/+/manifests"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
